server:
  port: 8004
 
spring:
  activemq:
    broker-url: tcp://192.168.23.134:61616
    user: admin
    password: admin
    
eureka: 
  client: 
    serviceUrl:
      defaultZone:  http://192.168.23.134:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
    
notification: 
  request: 
    queue: NOTIFICATION_QUEUE